exclude = [
    'https://fonts.gstatic.com/',
    'https://fonts.googleapis.com/',
    'http://go/github',
    'http://go/github-googlecloudplatform',
    'https://medium.com/',
    'https://x.com/',
    'http://localhost:12000/',
    'http://localhost:10020/',
    'https://www.askmarvin.ai/',
    'https://www.bcg.com/',
    'https://www.oracle.com/netsuite',
    'https://www.spglobal.com/',
    'https://www.epam.com/',
    'https://www.servicenow.com/',
    'https://www.almawave.com/it/',
    'https://www.adobe.com/',
    'https://www.autodesk.com/',
    'https://www.mckinsey.com/',
]
exclude_path = [
    ".github/actions/spelling",
    "CHANGELOG.md",
]

accept = ["200..=299", 403, 408, 429]

max_retries = 0
skip_missing = true
