name: A2AMonitor
options:
  bundleIdPrefix: com.a2a
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
settings:
  DEVELOPMENT_TEAM: ""
  CODE_SIGN_IDENTITY: ""
  CODE_SIGNING_REQUIRED: "NO"
  CODE_SIGNING_ALLOWED: "NO"
targets:
  A2AMonitor:
    type: application
    platform: iOS
    sources:
      - path: Sources/A2AMonitor
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.a2a.monitor
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
