{{- if and .Values.secret.create .Values.auth.enabled .Values.auth.tokens }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "a2a-server.fullname" . }}-auth
  labels:
    {{- include "a2a-server.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with include "a2a-server.annotations" . }}
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $tokens := list }}
  {{- range $key, $value := .Values.auth.tokens }}
  {{- $tokens = append $tokens (printf "%s:%s" $key $value) }}
  {{- end }}
  A2A_AUTH_TOKENS: {{ join "," $tokens | b64enc | quote }}
{{- end }}