apiVersion: v1
kind: Service
metadata:
  name: {{ include "a2a-server.fullname" . }}
  labels:
    {{- include "a2a-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with include "a2a-server.annotations" . }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.service.mcp.enabled }}
    - port: {{ .Values.service.mcp.port }}
      targetPort: {{ .Values.service.mcp.targetPort }}
      protocol: TCP
      name: mcp-http
    {{- end }}
  selector:
    {{- include "a2a-server.selectorLabels" . | nindent 4 }}