{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a2a-server.serviceAccountName" . }}
  labels:
    {{- include "a2a-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with include "a2a-server.annotations" . }}
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}